//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaltedChefLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public Nullable<System.TimeSpan> StartMonday { get; set; }
        public Nullable<System.TimeSpan> EndMonday { get; set; }
        public Nullable<System.TimeSpan> StartTuesday { get; set; }
        public Nullable<System.TimeSpan> EndTuesday { get; set; }
        public Nullable<System.TimeSpan> StartWednesday { get; set; }
        public Nullable<System.TimeSpan> EndWednesday { get; set; }
        public Nullable<System.TimeSpan> StartThursday { get; set; }
        public Nullable<System.TimeSpan> EndThursday { get; set; }
        public Nullable<System.TimeSpan> StartFriday { get; set; }
        public Nullable<System.TimeSpan> EndFriday { get; set; }
        public Nullable<System.TimeSpan> StartSaturday { get; set; }
        public Nullable<System.TimeSpan> EndSaturday { get; set; }
        public Nullable<System.TimeSpan> StartSunday { get; set; }
        public Nullable<System.TimeSpan> EndSunday { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
