//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaltedChefLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientNeed
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public bool StoveOven { get; set; }
        public string Allergies { get; set; }
        public string DietRestrictions { get; set; }
        public string DietGoals { get; set; }
        public bool OrganicMeals { get; set; }
        public string PreferredMeats { get; set; }
        public string MeatsToAvoid { get; set; }
        public string PreferredCheeses { get; set; }
        public string CheesesToAvoid { get; set; }
        public string PreferredGrains { get; set; }
        public string GrainsToAvoid { get; set; }
        public string SpiceLevel { get; set; }
        public string OtherToAvoid { get; set; }
        public string MainDishSoupSaladStew { get; set; }
        public string MealSize { get; set; }
        public bool StoreContainers { get; set; }
        public string PreferredGroceryStore { get; set; }
        public string ExtraNotes { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
