//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaltedChefLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMenu
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public int ClientId { get; set; }
        public int ScheduleId { get; set; }
        public string MenuNotes { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
