//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaltedChefLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int Id { get; set; }
        public int ScheduleId { get; set; }
        public string ImagePath { get; set; }
        public decimal Cost { get; set; }
        public decimal Charged { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
