//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaltedChefLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaltedChefEntities : DbContext
    {
        public SaltedChefEntities()
            : base("name=SaltedChefEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Availability> Availabilities { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientMenu> ClientMenus { get; set; }
        public virtual DbSet<ClientNeed> ClientNeeds { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<TimeSheet> TimeSheets { get; set; }
        public virtual DbSet<ZipAvailability> ZipAvailabilities { get; set; }
    }
}
